### PR TITLE
Complete rewrite of the flask app

### PR DESCRIPTION
**Pull request by mwilli20**
Hey guys so looking for some feedback before I go to much further. This is mostly a clean up to try and make the whole code base much easier to get into hack in. If you take a look at the branch, the basic idea is most commands can be used through the makefile to lint, test, format, and run the code. Besides that the logic breaks down as so:

- The init holds the construction of the app as well the routes.
- Then the coa_logic (terrible name) handles all the logic of calculating these routes
- And then in the future I would suggest we have a db_accessor to grab the data. This would make adding mocks and tests easier.

But I was just looking to see what people thought so far / would we like to go and remove the sqlalchacmey in favor of just writing sql. I feel like most don't know this specific ORM vs just sql in general.

### CODE REVIEW

**Comment by mwilli20** [comment]
#24 Related

**Comment by maithuvenkatesh** [comment]
Went through this with Matt and it looks good to me.

**Comment by mwilli20** [comment]
The location hierarchy route was added for this: https://github.com/CleanOceanAction/coa_ui/issues/24 and simply as a test to see how easy it is to iterate on.

**Comment by mwilli20** [comment]
## Status Update

#### Done

- ORM Removal: All but two routes have been converted over.
    - We decided to go with the `mysqldb` direct route as that will enable us to have the same code in the legacy app, which needs to be ported over, and the current code.
    - Also most seem to prefer the `SQL` directly over the `ORM`, which I agree with.
- Code Quality Enchantments
    - All code is formatted 
    - 10.0/10.0 on pylint with zero pylintrc exceptions
    - Fully type annotated with mypy with zero errors or warnings
    - All the code is documented with full (minus the non converted )
- Security: All dependencies have been patched up so no more security issues.
-  DevX Enchantments:
    - Created a Makefile with a help to describe common actions you can perform in the repo.
    - These will use make and the pipenv to handle the virtualenv and pip for the project seamlessly while allowing easy access to run, lint, fmt, etc with ease.

#### Left

- Convert over the other two routes while maintaining the same code quality standard.

That's it, we want to merge this in and allow for more smaller and  much more granular PRs in the future.

Once again sorry this is all in one, for the sake of merge conflicts, I think its better.

**Comment by mwilli20** [comment]
One route left

**Comment by mwilli20** [comment]
@maithuvenkatesh @jerrylin1218 Hey guys I finished with the rest of the routes, would be good to see if you guys can build / test this code easily on your machines and also give it the old review. But this should have the complete rewrite, and hopefully get us back on a more rapid iteration cycle of small PRs.

**Comment by mwilli20** [comment]
Considering how big this change is I think we should probably wait until @maithuvenkatesh gets to make sure she doesn't have any thoughts before we merge.

**Comment by mwilli20** [comment]
Merging as this has been open for a while and was approved.

**Pull request merged**
